name: Mobile Apps CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'ios/**'
      - 'android/**'
      - '.github/workflows/mobile-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'ios/**'
      - 'android/**'

jobs:
  ios:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios && pod install
      
      - name: Build iOS app
        working-directory: ./ios
        run: |
          xcodebuild -workspace DepositoUrbano.xcworkspace \
            -scheme DepositoUrbano \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14' \
            build
      
      - name: Run iOS tests
        working-directory: ./ios
        run: |
          xcodebuild test -workspace DepositoUrbano.xcworkspace \
            -scheme DepositoUrbanoTests \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14'

  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Grant execute permission for gradlew
        working-directory: ./android
        run: chmod +x gradlew
      
      - name: Build Android app
        working-directory: ./android
        run: ./gradlew assembleDebug
      
      - name: Run Android tests
        working-directory: ./android
        run: ./gradlew test
      
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk